env:
  es6: true
  node: true
  mocha: true
extends:
  - 'eslint:recommended'
  - 'prettier'
parserOptions:
  ecmaVersion: 13
  sourceType: script
rules:
  no-unused-vars:
    - error
    - args: none
  no-console: warn
  curly: error
  eqeqeq: error
  no-throw-literal: error
  strict: error
  no-var: error
  dot-notation: error
  no-tabs: error
  #HQ: We keep no-tabs because Prettier also enforces spaces.
  # no-use-before-define: error
  no-useless-call: error
  no-with: error
  require-jsdoc:
    - error
    - require:
        ClassDeclaration: true
        MethodDefinition: true
        FunctionDeclaration: true
  valid-jsdoc:
    - error
    - requireReturn: false
  yoda: error
