export const CodeGen: {
    AbstractPlugin: typeof import("./lib/codegen/abstractplugin");
    GoLangVisitor: typeof import("./lib/codegen/fromcto/golang/golangvisitor");
    JSONSchemaVisitor: typeof import("./lib/codegen/fromcto/jsonschema/jsonschemavisitor");
    XmlSchemaVisitor: typeof import("./lib/codegen/fromcto/xmlschema/xmlschemavisitor");
    PlantUMLVisitor: typeof import("./lib/codegen/fromcto/plantuml/plantumlvisitor");
    TypescriptVisitor: typeof import("./lib/codegen/fromcto/typescript/typescriptvisitor");
    JavaVisitor: typeof import("./lib/codegen/fromcto/java/javavisitor");
    GraphQLVisitor: typeof import("./lib/codegen/fromcto/graphql/graphqlvisitor");
    CSharpVisitor: typeof import("./lib/codegen/fromcto/csharp/csharpvisitor");
    ODataVisitor: typeof import("./lib/codegen/fromcto/odata/odatavisitor");
    MermaidVisitor: typeof import("./lib/codegen/fromcto/mermaid/mermaidvisitor");
    MarkdownVisitor: typeof import("./lib/codegen/fromcto/markdown/markdownvisitor");
    ProtobufVisitor: typeof import("./lib/codegen/fromcto/protobuf/protobufvisitor");
    OpenApiVisitor: typeof import("./lib/codegen/fromcto/openapi/openapivisitor");
    AvroVisitor: typeof import("./lib/codegen/fromcto/avro/avrovisitor");
    JSONSchemaToConcertoVisitor: typeof import("./lib/codegen/fromJsonSchema/cto/jsonSchemaVisitor");
    OpenApiToConcertoVisitor: typeof import("./lib/codegen/fromOpenApi/cto/openApiVisitor");
    RustVisitor: typeof import("./lib/codegen/fromcto/rust/rustvisitor");
    VocabularyVisitor: typeof import("./lib/codegen/fromcto/vocabulary/vocabularyvisitor");
    BenchmarkModelGenerator: typeof import("./lib/common/benchmarkModelGenerator");
    formats: {
        golang: typeof import("./lib/codegen/fromcto/golang/golangvisitor");
        jsonschema: typeof import("./lib/codegen/fromcto/jsonschema/jsonschemavisitor");
        xmlschema: typeof import("./lib/codegen/fromcto/xmlschema/xmlschemavisitor");
        plantuml: typeof import("./lib/codegen/fromcto/plantuml/plantumlvisitor");
        typescript: typeof import("./lib/codegen/fromcto/typescript/typescriptvisitor");
        java: typeof import("./lib/codegen/fromcto/java/javavisitor");
        graphql: typeof import("./lib/codegen/fromcto/graphql/graphqlvisitor");
        csharp: typeof import("./lib/codegen/fromcto/csharp/csharpvisitor");
        odata: typeof import("./lib/codegen/fromcto/odata/odatavisitor");
        mermaid: typeof import("./lib/codegen/fromcto/mermaid/mermaidvisitor");
        markdown: typeof import("./lib/codegen/fromcto/markdown/markdownvisitor");
        protobuf: typeof import("./lib/codegen/fromcto/protobuf/protobufvisitor");
        openapi: typeof import("./lib/codegen/fromcto/openapi/openapivisitor");
        avro: typeof import("./lib/codegen/fromcto/avro/avrovisitor");
        rust: typeof import("./lib/codegen/fromcto/rust/rustvisitor");
        vocabulary: typeof import("./lib/codegen/fromcto/vocabulary/vocabularyvisitor");
    };
};
export const Common: typeof import("./lib/common/common");
export const version: any;
export const AbstractPlugin: typeof import("./lib/codegen/abstractplugin");
export const GoLangVisitor: typeof import("./lib/codegen/fromcto/golang/golangvisitor");
export const JSONSchemaVisitor: typeof import("./lib/codegen/fromcto/jsonschema/jsonschemavisitor");
export const XmlSchemaVisitor: typeof import("./lib/codegen/fromcto/xmlschema/xmlschemavisitor");
export const PlantUMLVisitor: typeof import("./lib/codegen/fromcto/plantuml/plantumlvisitor");
export const TypescriptVisitor: typeof import("./lib/codegen/fromcto/typescript/typescriptvisitor");
export const JavaVisitor: typeof import("./lib/codegen/fromcto/java/javavisitor");
export const GraphQLVisitor: typeof import("./lib/codegen/fromcto/graphql/graphqlvisitor");
export const CSharpVisitor: typeof import("./lib/codegen/fromcto/csharp/csharpvisitor");
export const ODataVisitor: typeof import("./lib/codegen/fromcto/odata/odatavisitor");
export const MermaidVisitor: typeof import("./lib/codegen/fromcto/mermaid/mermaidvisitor");
export const MarkdownVisitor: typeof import("./lib/codegen/fromcto/markdown/markdownvisitor");
export const ProtobufVisitor: typeof import("./lib/codegen/fromcto/protobuf/protobufvisitor");
export const OpenApiVisitor: typeof import("./lib/codegen/fromcto/openapi/openapivisitor");
export const AvroVisitor: typeof import("./lib/codegen/fromcto/avro/avrovisitor");
export const JSONSchemaToConcertoVisitor: typeof import("./lib/codegen/fromJsonSchema/cto/jsonSchemaVisitor");
export const OpenApiToConcertoVisitor: typeof import("./lib/codegen/fromOpenApi/cto/openApiVisitor");
export const RustVisitor: typeof import("./lib/codegen/fromcto/rust/rustvisitor");
export const VocabularyVisitor: typeof import("./lib/codegen/fromcto/vocabulary/vocabularyvisitor");
export const BenchmarkModelGenerator: typeof import("./lib/common/benchmarkModelGenerator");
export const DiagramVisitor: typeof import("./lib/common/diagramvisitor");
export const ConcertoGraphVisitor: typeof import("./lib/common/graph").ConcertoGraphVisitor;
export const DirectedGraph: typeof import("./lib/common/graph").DirectedGraph;
